name: skbuild

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 2
  CTEST_OUTPUT_ON_FAILURE: 1
  CXXFLAGS: "-Wall -Wextra -Wpedantic -march=broadwell"

jobs:
  wheel:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - name: Fixup Run actions/checkout
      run: git config --global --add safe.directory '*'
    - uses: pypa/cibuildwheel@v2.16
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl
