name: skbuild

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 2
  CTEST_OUTPUT_ON_FAILURE: 1
  VERBOSE: 1

jobs:
  wheel:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4

    - name: Install vcpkg dependencies
      uses: ./.github/actions/setup-vcpkg

    - uses: pypa/cibuildwheel@v2.16
      env:
        CIBW_ENVIRONMENT_LINUX: >-
          VCPKG_OVERLAY_PORTS=/host/${{ env.VCPKG_OVERLAY_PORTS }}
          VCPKG_INSTALLATION_ROOT=/host/${{ env.VCPKG_INSTALLATION_ROOT }}
          CMAKE_TOOLCHAIN_FILE=/host/${{ env.CMAKE_TOOLCHAIN_FILE }}
        CIBW_ENVIRONMENT_PASS_LINUX: >-
          ACTIONS_RUNTIME_TOKEN
          ACTIONS_CACHE_URL
          VCPKG_BINARY_SOURCES
          VERBOSE

    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl
