name: skbuild

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:

# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
env:
  CMAKE_BUILD_PARALLEL_LEVEL: 2
  CTEST_PARALLEL_LEVEL: 2
  CTEST_OUTPUT_ON_FAILURE: 1
  CXXFLAGS: "-Wall -Wextra -Wpedantic -march=broadwell"

jobs:
  wheel:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
        - os: macos-latest
        - os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: echo "CIBW_BEFORE_ALL=yum install -y gsl-devel" >> $GITHUB_ENV
    - name: Install macOS dependencies
      if: runner.os == 'macOS'
      run: brew install gsl
    - name: Install Windows dependencies
      if: runner.os == 'Windows'
      run: |
        vcpkg install --triplet x64-windows
        echo "CMAKE_TOOLCHAIN_FILE=${env:VCPKG_INSTALLATION_ROOT}\scripts\buildsystems\vcpkg.cmake" | Tee-Object -FilePath ${env:GITHUB_ENV} -Append
    - uses: pypa/cibuildwheel@v2.16
    - name: Upload wheels
      uses: actions/upload-artifact@v3
      with:
        path: wheelhouse/*.whl
